# Generated by Django 3.2.5 on 2021-12-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('profile_image', models.CharField(max_length=300)),
                ('profile_desc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
