# Generated by Django 3.2.5 on 2021-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=256)),
                ('email_address', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('profile_image', models.CharField(max_length=1000, null=True)),
                ('profile_bio', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
