# Generated by Django 4.0 on 2021-12-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='privacy',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='phonenumber',
        ),
    ]
