# Generated by Django 4.0 on 2021-12-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_privacy_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
